# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b655af2d076329e76b2eb66f92fc13064f7581b88237fbcca7bc14c1f56a707dc45a14a4edd928ab3eef13558a9f1a8cf6eddd36bfab3479ca9acead69436e3

test:
  secret_key_base: 34b327f3228bd83d31446c4d80b5f6b8549bcbd4c96780a6ca7f091ccd7ab3c709a4a979eb2815389dd74bae58e91304d75be368095f8f6c72f3f9bb63797fed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
